// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_taylorswift_ = (function() {
  function block_taylorswift_() {
    this.run = bind(this.run, this);
    var css;
    this.taylor_swift = {
      name: "taylor swift",
      instagram_id: 11830955
    };
    css = "#instafeed {\n	display: none;\n}\n\n#taylor-image {\n	height:130%;\n	position: relative;\n	left: -65px;\n	top:0px;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable celeb\" name=\"taylorswift\">\n	<img id=\"taylor-image\" src=\"img/taylorswift.jpg\">\n	<div id=\"instafeed\"></div>\n</div>").appendTo(".drag-zone");
  }

  block_taylorswift_.prototype.run = function() {
    return this.taylor_swift;
  };

  return block_taylorswift_;

})();
