// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_filter_ = (function() {
  function block_filter_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable filter\" name=\"filter\">\n	FILTER\n</div>").appendTo(".drag-zone");
  }

  block_filter_.prototype.run = function(element) {
    return true;
  };

  return block_filter_;

})();
