// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_action_ = (function() {
  function block_action_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable action\" name=\"action\">\n	ACTION\n</div>").appendTo(".drag-zone");
  }

  block_action_.prototype.run = function() {
    return "ACTION IS HERE";
  };

  return block_action_;

})();
