// Generated by CoffeeScript 1.6.2
var app, express, fs, http, https, options;

express = require('express');

https = require('https');

http = require('http');

fs = require('fs');

options = {
  key: fs.readFileSync('./server/key.key'),
  cert: fs.readFileSync('./server/crt.crt')
};

app = express();

http.createServer(app).listen(80);

https.createServer(options, app).listen(8000);

app.use(express["static"](__dirname));
