// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_soundcloud_ = (function() {
  function block_soundcloud_() {
    this.run = bind(this.run, this);
    var css;
    css = "#soundcloud {\n		background-image: url(img/soundcloud.png);\n		background-size: cover;\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id=\"soundcloud\" class=\"drag-wrap draggable source\" name=\"soundcloud\">\n</div>").appendTo(".drag-zone");
  }

  block_soundcloud_.prototype.run = function(element) {
    return console.log("SOUNDCLOUD RUN; no run function yet");
  };

  return block_soundcloud_;

})();
