// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_soundcloud_ = (function() {
  function block_soundcloud_() {
    this.run = bind(this.run, this);
    var css;
    css = "#soundcloud {\n		background-image: url(img/soundcloud.png);\n		background-size: cover;\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id=\"soundcloud\" class=\"drag-wrap draggable source\" name=\"soundcloud\">\n</div>").appendTo(".drag-zone");
  }

  block_soundcloud_.prototype.run = function(element) {
    var track_url;
    console.log("SOUNDCLOUD RUN");
    SC.initialize({
      client_id: '21269af4bcee636bc4e3036d5ae81daf'
    });
    track_url = 'http://soundcloud.com/donnietrumpet/sets/surf';
    return SC.oEmbed(track_url, {
      auto_play: true
    }, function(oEmbed) {
      console.log("oEmbed response:");
      return console.log(oEmbed);
    });
  };

  return block_soundcloud_;

})();
