// Generated by CoffeeScript 1.6.2
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_instagram_ = (function() {
  function block_instagram_() {
    this.loop_done = __bind(this.loop_done, this);
    this.run = __bind(this.run, this);
    var css;

    css = "[name=instagram] {\n	background-image: url(img/instagram.png);\n	background-size: cover;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable source\" name=\"instagram\">\n</div>\n<div id=\"instafeed\"></div>").appendTo(".drag-zone");
  }

  block_instagram_.prototype.run = function(celeb, cb) {
    var audio,
      _this = this;

    audio = new Audio("sound/" + celeb.name + ".mp3");
    audio.play();
    this.uploaded_count = 0;
    $("<img src='img/load2.gif' style='position:absolute;top:10px;left:10px;width:350px;height:auto;z-index:1004;'>").appendTo($("body"));
    $("<div id='compilation-animation' style='position:absolute;top:200px;left:90px;font-size:250%;color:white;z-index:1005;'>COMPILING</div>").appendTo($("body"));
    $("<div id='progress-animation' style='position:absolute;top:250px;left:80px;font-size:150%;color:white;z-index:1005;'>0 PICTURES LOADED</div>").appendTo($("body"));
    $("#new-button").remove();
    this.current_interval = 0;
    wait(500, function() {
      var cur, dots, _i, _ref;

      _this.current_interval++;
      if (_this.current_interval > 3) {
        _this.current_interval = 0;
      }
      dots = "";
      for (cur = _i = 0, _ref = _this.current_interval; _i < _ref; cur = _i += 1) {
        dots += ".";
      }
      return $("#compilation-animation").text("COMPILING" + dots);
    });
    this.all_posts = [];
    this.feed = new Instafeed({
      get: 'user',
      userId: celeb.instagram_id,
      accessToken: '2072221807.1677ed0.cfc898e6c7124300bb90d836f3e14e9d',
      clientId: 'f41df43206564056b252ae8a5cb4019e',
      limit: 60,
      error: function() {
        return console.log("instagram error");
      },
      success: function(json) {
        var cur, list, _i, _len;

        list = json.data;
        for (_i = 0, _len = list.length; _i < _len; _i++) {
          cur = list[_i];
          _this.uploaded_count++;
          _this.all_posts.push(cur);
        }
        $("#progress-animation").text("" + _this.uploaded_count + " PICTURES LOADED");
        return setTimeout(_this.loop_done, 0, cb);
      }
    });
    return this.feed.run();
  };

  block_instagram_.prototype.loop_done = function(cb) {
    if (this.feed.hasNext()) {
      return this.feed.next();
    } else {
      return cb(this.all_posts);
    }
  };

  return block_instagram_;

})();
