// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_play_audio_ = (function() {
  function block_play_audio_() {
    this.run = bind(this.run, this);
    var css;
    css = "		";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable action\" name=\"play_audio\">\n	PLAY AUDIO\n</div>").appendTo(".drag-zone");
  }

  block_play_audio_.prototype.run = function(obj, cb) {
    var audio;
    audio = new Audio();
    audio.src = obj.preview_url;
    $(audio).bind('ended', function() {
      return cb();
    });
    return audio.play();
  };

  return block_play_audio_;

})();
