// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_caption_ = (function() {
  function block_caption_() {
    this.run = bind(this.run, this);
    var css;
    css = "[name=caption] {\n	font-size: 25px;\n}\n#caption_input {\n	position: absolute;\n	top: 55%;\n	width: 80%;\n	left: 6%;\n	text-align: center;\n	font-size: 12px;\n}\n\ninput[type='text'],\ninput[type='number'],\ntextarea {\n	font-size: 16px;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable filter\" name=\"caption\">\n	CAPTION\n	<input id=\"caption_input\" type=\"text\" value=\"\">\n</div>").appendTo(".drag-zone");
    interact("[name=caption]").on('tap click', (function(_this) {
      return function(event) {
        event.preventDefault();
        return $("#caption_input").focus();
      };
    })(this));
  }

  block_caption_.prototype.run = function(element) {
    var input;
    input = $("#caption_input").val().toLowerCase();
    if (element.caption !== null && element.caption.text.indexOf(input) !== -1) {
      return true;
    }
    return false;
  };

  return block_caption_;

})();
