// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_users_in_photo_ = (function() {
  function block_users_in_photo_() {
    this.run = bind(this.run, this);
    var css;
    css = "[name=users_in_photo] {\n	font-size: 30px;\n}\n#username_input" + window.users_counter + " {\n	position: absolute;\n	top: 55%;\n	width: 80%;\n	left: 6%;\n	text-align: center;\n	font-size: 12px;\n}\n\ninput[type='text'],\ninput[type='number'],\ntextarea {\n	font-size: 16px;\n}";
    $('<style type="text/css"></style>').html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable filter\" name=\"users_in_photo\">\n	WITH @\n	<input id=\"username_input" + window.users_counter + "\" type=\"\" value=\"\">\n</div>").appendTo(".drag-zone");
    interact("[name=users_in_photo]").on('tap click', (function(_this) {
      return function(event) {
        event.preventDefault();
        return $("#username_input" + window.users_counter).focus();
      };
    })(this));
  }

  block_users_in_photo_.prototype.run = function(element) {
    var friend, full_name, i, input, len, ref, username;
    input = $("#username_input" + window.users_counter).val();
    ref = element.users_in_photo;
    for (i = 0, len = ref.length; i < len; i++) {
      friend = ref[i];
      username = friend.user.username;
      full_name = friend.user.full_name.toLowerCase();
      if (input === username || input.toLowerCase() === full_name) {
        return true;
      }
    }
    return false;
  };

  return block_users_in_photo_;

})();
