// Generated by CoffeeScript 1.9.3
var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

this.block_hashtag_ = (function() {
  function block_hashtag_() {
    this.run = bind(this.run, this);
    var css;
    css = ".hashtags {\n	position: relative;\n}\n\ninput[name='hashtaginput'] {\n	position: absolute;\n	left: 40px;\n	top: 50px;\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div class=\"drag-wrap draggable filter hashtags\" name=\"hashtag\">\n	<!--<form>\n		#<input type=\"text\" name=\"hashtaginput\">\n	</form>-->\n	<form action=\"demo_form.asp\" style=\"z-index:'1000000000'\">\n		First name: <input type=\"text\" name=\"hashtaginput\" value=\"Mickey\"><br>\n		Last name: <input type=\"text\" name=\"LastName\" value=\"Mouse\"><br>\n		<input type=\"submit\" value=\"Submit\">\n	</form>\n</div>").appendTo(".drag-zone");
  }

  block_hashtag_.prototype.run = function(element) {
    var likes, tags;
    console.log(element);
    likes = element.likes.count;
    return tags = element.tags;
  };

  return block_hashtag_;

})();
