// Generated by CoffeeScript 1.6.2
this.control_drop_area_ = (function() {
  function control_drop_area_() {
    var css;

    css = ".drop_area {\n	position: relative;\n}\n\n#new-button {\n\n}";
    $("<style type='text/css'></style>").html(css).appendTo("head");
    $("<div id='current-step' class='text'></div>\n<div class='drop_area' role='drop_area'></div>").appendTo($("body"));
    this.zones = 1;
    this.celebrity = new control_drag_zone_(5, 50, 365, 'celeb');
  }

  control_drop_area_.prototype.expand = function() {
    var current_counter;

    current_counter = window.counter;
    switch (current_counter) {
      case 1:
        return this.source = new control_drag_zone_(45, 75, 205, 'source');
      case 2:
        return this.filter = new control_drag_zone_(125, 75, 205, 'filter');
      case 3:
        return this.action = new control_drag_zone_(85, 182, 205, 'action');
      case 4:
        return this.create_button();
    }
  };

  control_drop_area_.prototype.create_button = function() {
    var $blacken, $new_div,
      _this = this;

    $blacken = $("<div></div>").css({
      'z-index': '500',
      'opacity': '0.5',
      'background-color': 'black',
      width: '100%',
      height: '100%',
      position: 'absolute',
      left: '0px',
      top: '0px'
    });
    $("body").prepend($blacken);
    $new_div = $("<div id=\"new-button\">\n	<p style='position:absolute;font-size: 25px;left:17px;top:5px;' >RUN!</p>\n</div>");
    $new_div.css({
      borderRadius: 100,
      width: 90,
      height: 90,
      position: 'absolute',
      top: 180,
      left: 140,
      zIndex: 10000,
      backgroundColor: 'white'
    });
    $("body").prepend($new_div);
    $new_div.addClass('can--drop');
    return $new_div.bind('tap click', function() {
      return _this.run();
    });
  };

  control_drop_area_.prototype.run = function() {
    var celeb_name,
      _this = this;

    celeb_name = this.celebrity.run();
    return this.source.run(celeb_name, function(list, outer_cb) {
      return async.forEachOfSeries(list, function(element, i, cb) {
        if (_this.filter.run(element)) {
          _this.action.run(element, cb);
        } else {
          cb();
        }
      }, function(err) {
        if (outer_cb != null) {
          return outer_cb();
        } else {
          return console.log("LOOP ENDED W/O OUTER_CB");
        }
      });
    });
  };

  return control_drop_area_;

})();
